# Web Scraping

### To events.csv

In [40]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [41]:
URL = "https://en.wikipedia.org/wiki/Timeline_of_Korean_history"
page = requests.get(URL)

In [42]:
soup = BeautifulSoup(page.content, "html.parser")

In [43]:
dynasties = {"1": "Joseon", "2": "Goryeo"}
data_dict = {
    "year": [],
    "description": [],
    "period": [],
    "dynasty_id": []
}
def extract_dynasty(idx, dynasty):
    h2_dynasty = soup.find(id=dynasty)
    country_name = h2_dynasty.text
    ul_dynasty = h2_dynasty.findNext("ul")
    
    for li in ul_dynasty:
        info = li.text.replace("\\n", "").strip().split(":")
        if len(info) == 2:
            year = info[0]
            content = info[1].strip()
            data_dict["year"].append(year)
            data_dict["description"].append(content)
            data_dict["period"].append(str(int(year[:2]) + 1) + " century")
            data_dict["dynasty_id"].append(idx)

In [44]:
for dynasty_idx in dynasties:
    extract_dynasty(dynasty_idx,dynasties[dynasty_idx])

In [45]:
df = pd.DataFrame(data_dict)

In [46]:
df

,year,description,period,dynasty_id
0,1392,"Yi Seonggye is crowned king, officially beginn...",14 century,1
1,1394,Capital moved to Hanyang (modern-day Seoul),14 century,1
2,1402,Paper currency initiated,15 century,1
3,1408,High military service examination system created,15 century,1
4,1420,Hall of Worthies established,15 century,1
5,1424,History of Goryeo compiled,15 century,1
6,1446,"The Hangul alphabet, created 3 years earlier, ...",15 century,1
7,1592,The Japanese invasion of Korea begins under th...,16 century,1
8,1627,The Later jin invasion of Korea,17 century,1
9,1653,"Dutch ship, with Captain Hendrick Hamel, wreck...",17 century,1
10,1791,Persecution of Catholicism begins.,18 century,1
11,1864,"Gojong ascends the throne with his father, Dae...",19 century,1
12,1866,French Campaign against Korea.,19 century,1
13,1871,United States expedition to Korea.,19 century,1
14,1876,Korean ports are formally opened under the Tre...,19 century,1
15,1884,"Kim Okgyun leads the Gapsin Coup. In 3 days, C...",19 century,1
16,1894,Donghak Rebellion prompts the First Sino-Japan...,19 century,1
17,1895,China recognizes Korean independence in the Tr...,19 century,1
18,1896,11 February. King Gojong flees to the Russian ...,19 century,1
19,936,Goryeo completes the reunification of the Late...,94 century,2
20,956,Emperor Gwangjong forces major land and slaver...,96 century,2
21,993,The first of three Goryeo–Khitan Wars.,100 century,2
22,1010,The Second Goryeo–Khitan War ravages the north...,11 century,2
23,1018,"The Third Goryeo–Khitan War, Khitan successful...",11 century,2
24,1033,"Goryeo builds the Cheonri Jangseong (lit. ""Tho...",11 century,2
25,1145,"Kim Bu-sik compiles the Samguk Sagi, Korea's o...",12 century,2
26,1170,The military coup.,12 century,2
27,1231,The Mongol invasions of Korea begin,13 century,2
28,1234,Choi Yun-ui's Sangjeong Gogeum Yemun is publis...,13 century,2
29,1251,"Goryeo completes the Tripitaka Koreana, the mo...",13 century,2
30,1268,Mongol peace treaty is signed which Mongols ag...,13 century,2
31,1270,"Goryeo signs a peace treaty with the Mongols, ...",13 century,2
32,1285,"Il-yeon compiles the Samguk Yusa, record of hi...",13 century,2
33,1388,"General Yi Seonggye, ordered to engage China i...",14 century,2

In [47]:
df.isnull().sum()

year           0
description    0
period         0
dynasty_id     0
dtype: int64

In [48]:
df.to_csv("korea.csv")

In [49]:
df.to_csv("events.csv", mode="a", header=False)

### Joseon

In [13]:
h2_joseon = soup.find(id="Joseon")
country_name = h2_joseon.text

In [14]:
h2_joseon

In [15]:
ul_joseon = h2_joseon.findNext("ul")

In [16]:
COUNTRY = "N/S Korea"
data_dict = {
    "year": [],
    "description": [],
    "period": [],
    "current_country": [],
    "country": []
}
for li in ul_joseon:
    info = li.text.replace("\\n", "").strip().split(":")
    if len(info) == 2:
        year = info[0]
        content = info[1].strip()
        data_dict["year"].append(year)
        data_dict["description"].append(content)
        data_dict["period"].append(str(int(year[:2]) + 1) + " century")
        data_dict["current_country"].append(COUNTRY)
        data_dict["country"].append(country_name)

In [17]:
df = pd.DataFrame(data_dict)

In [18]:
df

,year,description,period,current_country,country
0,1392,"Yi Seonggye is crowned king, officially beginn...",14 century,N/S Korea,Joseon
1,1394,Capital moved to Hanyang (modern-day Seoul),14 century,N/S Korea,Joseon
2,1402,Paper currency initiated,15 century,N/S Korea,Joseon
3,1408,High military service examination system created,15 century,N/S Korea,Joseon
4,1420,Hall of Worthies established,15 century,N/S Korea,Joseon
5,1424,History of Goryeo compiled,15 century,N/S Korea,Joseon
6,1446,"The Hangul alphabet, created 3 years earlier, ...",15 century,N/S Korea,Joseon
7,1592,The Japanese invasion of Korea begins under th...,16 century,N/S Korea,Joseon
8,1627,The Later jin invasion of Korea,17 century,N/S Korea,Joseon
9,1653,"Dutch ship, with Captain Hendrick Hamel, wreck...",17 century,N/S Korea,Joseon
10,1791,Persecution of Catholicism begins.,18 century,N/S Korea,Joseon
11,1864,"Gojong ascends the throne with his father, Dae...",19 century,N/S Korea,Joseon
12,1866,French Campaign against Korea.,19 century,N/S Korea,Joseon
13,1871,United States expedition to Korea.,19 century,N/S Korea,Joseon
14,1876,Korean ports are formally opened under the Tre...,19 century,N/S Korea,Joseon
15,1884,"Kim Okgyun leads the Gapsin Coup. In 3 days, C...",19 century,N/S Korea,Joseon
16,1894,Donghak Rebellion prompts the First Sino-Japan...,19 century,N/S Korea,Joseon
17,1895,China recognizes Korean independence in the Tr...,19 century,N/S Korea,Joseon
18,1896,11 February. King Gojong flees to the Russian ...,19 century,N/S Korea,Joseon

In [19]:
df.isnull().sum()

year               0
description        0
period             0
current_country    0
country            0
dtype: int64

In [20]:
df.to_csv("korea.csv")